/**
 * Export and Graphic Sharing Engine
 * Generates Standings PNG, Season PDF Report, and Match Result Broadcast Cards.
 */

import * as Store from '../store.js';
import { showLoading, customAlert, getTeamLogo } from '../ui/core.js';
import { fetchAPI } from './schedule.js';

export async function exportStandingsImage() {
    const target = document.getElementById('tab-standing');
    if (!target) return;

    showLoading(true);
    try {
        if (typeof html2canvas === 'undefined') {
            throw new Error("Library html2canvas tidak tersedia.");
        }
        const canvas = await html2canvas(target, {
            backgroundColor: getComputedStyle(document.body).getPropertyValue('--bg-main'),
            scale: 2
        });
        const url = canvas.toDataURL("image/png");
        const a = document.createElement('a');
        a.href = url;
        const dateStr = new Date().toISOString().split('T')[0];
        a.download = `MPL_Standings_${Store.activeSessionName}_${dateStr}.png`;
        a.click();
    } catch (e) {
        console.error(e);
        customAlert("Gagal mengekspor gambar klasemen.");
    } finally {
        showLoading(false);
    }
}

export async function exportSeasonReport() {
    if (!window.jspdf || !window.jspdf.jsPDF) {
        customAlert("Library jsPDF tidak tersedia.");
        return;
    }

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    showLoading(true);

    try {
        const teams = await fetchAPI('get_standings');
        const sessionName = Store.activeSessionName || 'MPL Season';

        // Header
        doc.setFillColor(155, 17, 30);
        doc.rect(0, 0, 210, 40, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.setFont("helvetica", "bold");
        doc.text("MPL SEASON REPORT", 105, 20, { align: "center" });

        doc.setFontSize(11);
        doc.setFont("helvetica", "normal");
        doc.text(`Simulator Session: ${sessionName}`, 105, 30, { align: "center" });

        // Standings Table
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("Regular Season Final Standings", 20, 55);

        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.text("Pos", 20, 65);
        doc.text("Team", 35, 65);
        doc.text("W", 100, 65);
        doc.text("L", 115, 65);
        doc.text("Points", 130, 65);
        doc.text("Win Rate", 160, 65);

        doc.setLineWidth(0.5);
        doc.line(20, 67, 190, 67);

        doc.setFont("helvetica", "normal");
        (teams || []).forEach((t, i) => {
            const y = 75 + (i * 10);
            doc.text((i + 1).toString(), 20, y);
            doc.text(`${t.team_name} (${t.tag})`, 35, y);
            doc.text((t.match_win || 0).toString(), 100, y);
            doc.text((t.match_lose || 0).toString(), 115, y);
            doc.text((t.points || 0).toString(), 130, y);
            const wr = t.match_played > 0 ? Math.round((t.match_win / t.match_played) * 100) + '%' : '0%';
            doc.text(wr, 160, y);

            if (i < teams.length - 1) {
                doc.setDrawColor(230, 230, 230);
                doc.line(20, y + 3, 190, y + 3);
            }
        });

        // Footer
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Generated by MPLSim on ${new Date().toLocaleDateString('id-ID')}`, 105, 285, { align: "center" });

        doc.save(`${sessionName.replace(/\s+/g, '_')}_Season_Report.pdf`);
        customAlert("Laporan PDF berhasil diunduh.");
    } catch (e) {
        console.error(e);
        customAlert("Gagal membuat laporan PDF.");
    } finally {
        showLoading(false);
    }
}

export async function shareMatchResult(matchId) {
    const match = Store.globalMatches.find(m => m.id === matchId);
    if (!match) return;

    const tA = Store.globalTeams.find(t => t.id === match.team_a_id);
    const tB = Store.globalTeams.find(t => t.id === match.team_b_id);
    if (!tA || !tB) return;

    const container = document.createElement('div');
    container.style.position = 'fixed';
    container.style.left = '-9999px';
    container.style.top = '0';
    container.style.width = '800px';
    container.style.height = '500px';
    container.style.padding = '50px';
    container.style.background = '#0a0c10';
    container.style.color = 'white';
    container.style.fontFamily = 'Inter, sans-serif';
    container.style.display = 'flex';
    container.style.flexDirection = 'column';
    container.style.alignItems = 'center';
    container.style.justifyContent = 'center';
    container.style.zIndex = '-1000';

    container.innerHTML = `
        <div style="text-transform: uppercase; letter-spacing: 0.3em; font-weight: 900; color: #E11D48; margin-bottom: 12px; font-size: 16px;">Match Result</div>
        <div style="font-size: 12px; color: #fda4af; margin-bottom: 40px; text-transform: uppercase; letter-spacing: 0.15em;">Regular Season : Week ${match.week}</div>
        
        <div style="display: flex; align-items: center; justify-content: center; gap: 50px; width: 100%;">
            <div style="display: flex; flex-direction: column; align-items: center; width: 180px;">
                <div style="width: 120px; height: 120px; margin: 0 auto 16px;">
                    ${getTeamLogo(tA.tag, 'w-full h-full')}
                </div>
                <div style="font-family: Oswald, sans-serif; font-weight: 700; font-size: 28px; text-align: center;">${tA.tag}</div>
            </div>
            
            <div style="display: flex; align-items: center; gap: 24px;">
                <div style="font-family: Oswald, sans-serif; font-size: 96px; font-weight: 800; color: ${match.score_a > match.score_b ? '#10B981' : '#FFFFFF'};">${match.score_a}</div>
                <div style="font-size: 32px; color: #E11D48; font-weight: 300;">:</div>
                <div style="font-family: Oswald, sans-serif; font-size: 96px; font-weight: 800; color: ${match.score_b > match.score_a ? '#10B981' : '#FFFFFF'};">${match.score_b}</div>
            </div>
            
            <div style="display: flex; flex-direction: column; align-items: center; width: 180px;">
                <div style="width: 120px; height: 120px; margin: 0 auto 16px;">
                    ${getTeamLogo(tB.tag, 'w-full h-full')}
                </div>
                <div style="font-family: Oswald, sans-serif; font-weight: 700; font-size: 28px; text-align: center;">${tB.tag}</div>
            </div>
        </div>
        
        <div style="margin-top: 40px; text-align: center;">
            <div style="font-size: 9px; color: #64748b; text-transform: uppercase; letter-spacing: 0.25em;">Simulated with</div>
            <div style="font-family: Oswald, sans-serif; font-weight: 800; font-size: 20px; color: white; letter-spacing: 0.05em;">MPL<span style="color: #E11D48;">Sim</span> Studio</div>
        </div>
    `;

    document.body.appendChild(container);
    showLoading(true);

    try {
        if (typeof html2canvas === 'undefined') {
            throw new Error("Library html2canvas tidak tersedia.");
        }
        const canvas = await html2canvas(container, {
            scale: 2,
            backgroundColor: '#0a0c10'
        });
        const url = canvas.toDataURL("image/png");
        const a = document.createElement('a');
        a.href = url;
        a.download = `Match_${tA.tag}_vs_${tB.tag}_Result.png`;
        a.click();
    } catch (e) {
        console.error(e);
        customAlert("Gagal mengekspor grafik pertandingan.");
    } finally {
        if (container.parentNode) document.body.removeChild(container);
        showLoading(false);
    }
}
